In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [9]:
## Series Create a Single Column with Shape (rows,1)
data = {
    "a" : 1,
    "b" : 2,
    "c" : 3
}

pd.Series(data = data)

a    1
b    2
c    3
dtype: int64

In [10]:
pd.Series(data = data , index = ["a" , "b"])

a    1
b    2
dtype: int64

In [11]:
pd.Series(data = data  , index = ["a","b","c","d"])

a    1.0
b    2.0
c    3.0
d    NaN
dtype: float64

In [12]:
pd.Series(data = data  , index = [1,2,3])

1   NaN
2   NaN
3   NaN
dtype: float64

In [14]:
pd.Series(data = data  , index = ["a","b","c"] , dtype= float)

a    1.0
b    2.0
c    3.0
dtype: float64

In [17]:
d = pd.Series(data = data  , index = ["a","b","c"] , dtype= str)
d.dtypes

dtype('O')

In [19]:
pd.Series(data = data  , index = ["a","b","c"] , name = "Roll No.")

a    1
b    2
c    3
Name: Roll No., dtype: int64

In [26]:
res = pd.Series(data = data  , index = ["a","b","c"] , name = "Roll No.")
res.iloc[1] = 6
res

a    1
b    6
c    3
Name: Roll No., dtype: int64

# **Attributes**

In [20]:
res = pd.Series(data = data  , index = ["a","b","c"] , name = "Roll No.")

In [22]:
## Transpose
res.T

a    1
b    2
c    3
Name: Roll No., dtype: int64

In [27]:
## Dtypes
res.dtypes

dtype('int64')

In [29]:
## Finding Empty Rows
res.empty

False

In [30]:
## Flags
res.flags

<Flags(allows_duplicate_labels=True)>

In [34]:
## hasnans : Return True if there are Nan values
res1 = res.copy()
res1.iloc[1] = np.nan
print("Has Nan Values:",res1.hasnans)
print(res1)

Has Nan Values: True
a    1.0
b    NaN
c    3.0
Name: Roll No., dtype: float64


In [35]:
## iat : Access value by prviding index
res.iat[1]

6

In [36]:
## name :  Return Name of Series
res.name

'Roll No.'

In [37]:
## ndim : Find ndim of Series
res.ndim

1

In [38]:
## Values : Return Values of Seires
res.values

array([1, 6, 3])

In [40]:
## index : Return indexes of Series
res.index

Index(['a', 'b', 'c'], dtype='object')

# **Method**

In [43]:
## abs() : Return Absolute of Seires
res1 = res.copy()
res1.iloc[1] = -1
print(res1)

print(res1.abs())

a    1
b   -1
c    3
Name: Roll No., dtype: int64
a    1
b    1
c    3
Name: Roll No., dtype: int64


In [44]:
## add() : Adds Two Series
res1.add(res)

a    2
b    5
c    6
Name: Roll No., dtype: int64

In [47]:
## Between :
res1.between(1,3)

a     True
b    False
c     True
Name: Roll No., dtype: bool

In [49]:
## corr() : find correlation
res.corr(res1)

1.0

In [50]:
## where() : Return Where the Conditionis True
res.where(res > 4)

a    NaN
b    6.0
c    NaN
Name: Roll No., dtype: float64

In [53]:
#### index : Return index
index = ["Islamabad","Faisalabad","Lahore"]
dis = [342,532,234]
res = pd.Series(data = dis , index = index , name = "Coverage")
res.index

Index(['Islamabad', 'Faisalabad', 'Lahore'], dtype='object')

In [55]:
res.index = ["Isb","Fsd","Lhr"]
res

Isb    342
Fsd    532
Lhr    234
Name: Coverage, dtype: int64

In [59]:
### array : Return Numpy Array
res.array

<NumpyExtensionArray>
[342, 532, 234]
Length: 3, dtype: int64

In [60]:
### Values : Return Values of Series
res.values

array([342, 532, 234])

In [61]:
### Shape
res.shape

(3,)

In [62]:
### nbytes : Return Bytes used
res.nbytes

24

In [63]:
## Size : return size of series
res.size

3

In [65]:
## memorey_usage
res.memory_usage()

156

In [68]:
## astype
res1 = res.copy()
res1 = res1.astype(str)
res1.dtypes

dtype('O')

In [72]:
## lt : less then
res.lt(3)

Isb    False
Fsd    False
Lhr    False
Name: Coverage, dtype: bool

In [73]:
## gt : greater then
res.gt(3)

Isb    True
Fsd    True
Lhr    True
Name: Coverage, dtype: bool

In [74]:
## le : less then equal to
res.le(3)

Isb    False
Fsd    False
Lhr    False
Name: Coverage, dtype: bool

In [76]:
## ge = Greater then  equal to
res.ge(350)

Isb    False
Fsd     True
Lhr    False
Name: Coverage, dtype: bool

In [77]:
## between
res.between(3,350)

Isb     True
Fsd    False
Lhr     True
Name: Coverage, dtype: bool

In [80]:
### Product : Return Product of all element
res.product()

42574896

In [84]:
### describe
res.describe()

count      3.000000
mean     369.333333
std      150.868596
min      234.000000
25%      288.000000
50%      342.000000
75%      437.000000
max      532.000000
Name: Coverage, dtype: float64

In [85]:
## min
res.min()

234

In [86]:
# max
res.max()

532

In [87]:
##  mean
res.mean()

369.3333333333333

In [88]:
## std
res.std()

150.86859624631407

In [89]:
## variance
res.var()

22761.333333333332

In [91]:
## covariance
res.cov(res1)

22761.333333333336

In [92]:
## median
res.median()

342.0

In [93]:
## quantile
res.quantile(0.58)

372.4

In [94]:
## skew
res.skew()

0.7885185400775767

In [95]:
## unique
res.unique()

array([342, 532, 234])

In [96]:
## n_unique
res.nunique()

3

In [97]:
## value counts
res.value_counts()

Coverage
342    1
532    1
234    1
Name: count, dtype: int64

In [98]:
## idxmax
res.idxmax()

'Fsd'

In [99]:
## idxmin
res.idxmin()


'Lhr'

In [100]:
## reset_index
res.reset_index()

index  Coverage
0   Isb       342
1   Fsd       532
2   Lhr       234

In [103]:
## isnull
res.isnull()

Isb    False
Fsd    False
Lhr    False
Name: Coverage, dtype: bool

In [104]:
## sum
res.isnull().sum()

0

In [105]:
## any
res.isnull().any()

False

In [107]:
## sort_vales
res.sort_values(ascending = False)

Fsd    532
Isb    342
Lhr    234
Name: Coverage, dtype: int64

In [108]:
## sort_index
res.sort_index()

Fsd    532
Isb    342
Lhr    234
Name: Coverage, dtype: int64